/*
 * This work includes material taken from The Lazy GM's Resource Document by 
 * Michael E. Shea of SlyFlourish.com (https://www.slyflourish.com) and vailable at 
 * https://slyflourish.com/lazy_gm_resource_document.html. The Lazy GM's Resource 
 * Document is licensed under the Creative Commons Attribution 4.0 International 
 * License available at https://creativecommons.org/licenses/by/4.0/legalcode.

 * This work includes material taken from the System Reference Document 5.1 ("SRD 
 * 5.1") by Wizards of the Coast LLC and available at 
 * https://dnd.wizards.com/resources/systems-reference-document. The SRD 5.1 is 
 * licensed under the Creative Commons Attribution 4.0 International License 
 * available at https://creativecommons.org/licenses/by/4.0/legalcode.
 */

module.exports = {
  id: "100monumentstructures",
  title: "100 Monument Structures",
  content: [
    {
      type: "table",
      order: 0,
      data: [
        { item_num: 1, item: "Aerie" },
        { item_num: 2, item: "Altar" },
        { item_num: 3, item: "Aqueduct" },
        { item_num: 4, item: "Arcane circle" },
        { item_num: 5, item: "Archway" },
        { item_num: 6, item: "Aviary" },
        { item_num: 7, item: "Barrow" },
        { item_num: 8, item: "Battlefield" },
        { item_num: 9, item: "Bell" },
        { item_num: 10, item: "Bone pile" },
        { item_num: 11, item: "Boneyard" },
        { item_num: 12, item: "Bonfire" },
        { item_num: 13, item: "Brazier" },
        { item_num: 14, item: "Bridge" },
        { item_num: 15, item: "Cage" },
        { item_num: 16, item: "Cairn" },
        { item_num: 17, item: "Campsite" },
        { item_num: 18, item: "Canal" },
        { item_num: 19, item: "Carcass" },
        { item_num: 20, item: "Carriage" },
        { item_num: 21, item: "Cauldron" },
        { item_num: 22, item: "Cave" },
        { item_num: 23, item: "Cenotaph" },
        { item_num: 24, item: "Cesspit" },
        { item_num: 25, item: "Charnel pit" },
        { item_num: 26, item: "Columns" },
        { item_num: 27, item: "Crater" },
        { item_num: 28, item: "Crossroads" },
        { item_num: 29, item: "Crystal" },
        { item_num: 30, item: "Dome" },
        { item_num: 31, item: "Doorway" },
        { item_num: 32, item: "Earthmote" },
        { item_num: 33, item: "Effigy" },
        { item_num: 34, item: "Fighting pit" },
        { item_num: 35, item: "Firepit" },
        { item_num: 36, item: "Fossil" },
        { item_num: 37, item: "Fountain" },
        { item_num: 38, item: "Gallows" },
        { item_num: 39, item: "Gateway" },
        { item_num: 40, item: "Geode" },
        { item_num: 41, item: "Geyser" },
        { item_num: 42, item: "Graveyard" },
        { item_num: 43, item: "Gravestone" },
        { item_num: 44, item: "Grotto" },
        { item_num: 45, item: "Grove" },
        { item_num: 46, item: "Hollow" },
        { item_num: 47, item: "Huge skull" },
        { item_num: 48, item: "Idol" },
        { item_num: 49, item: "Illusion" },
        { item_num: 50, item: "Keep" },
        { item_num: 51, item: "Lantern" },
        { item_num: 52, item: "Machine" },
        { item_num: 53, item: "Mausoleum" },
        { item_num: 54, item: "Megalith" },
        { item_num: 55, item: "Meteorite" },
        { item_num: 56, item: "Midden" },
        { item_num: 57, item: "Mill" },
        { item_num: 58, item: "Mine" },
        { item_num: 59, item: "Mirror" },
        { item_num: 60, item: "Monolith" },
        { item_num: 61, item: "Monument" },
        { item_num: 62, item: "Mosaic" },
        { item_num: 63, item: "Nest" },
        { item_num: 64, item: "Obelisk" },
        { item_num: 65, item: "Orb" },
        { item_num: 66, item: "Orrery" },
        { item_num: 67, item: "Oubliette" },
        { item_num: 68, item: "Petrified creature" },
        { item_num: 69, item: "Pillar" },
        { item_num: 70, item: "Pit" },
        { item_num: 71, item: "Planar rift" },
        { item_num: 72, item: "Platform" },
        { item_num: 73, item: "Podium" },
        { item_num: 74, item: "Pool" },
        { item_num: 75, item: "Rock" },
        { item_num: 76, item: "Ruin" },
        { item_num: 77, item: "Sacred circle" },
        { item_num: 78, item: "Sarcophagus" },
        { item_num: 79, item: "Shipwreck" },
        { item_num: 80, item: "Shrine" },
        { item_num: 81, item: "Sigil" },
        { item_num: 82, item: "Sinkhole" },
        { item_num: 83, item: "Slab" },
        { item_num: 84, item: "Spell effect" },
        { item_num: 85, item: "Sphere" },
        { item_num: 86, item: "Spire" },
        { item_num: 87, item: "Statue" },
        { item_num: 88, item: "Stone circle" },
        { item_num: 89, item: "Stone tablets" },
        { item_num: 90, item: "Sundial" },
        { item_num: 91, item: "Throne" },
        { item_num: 92, item: "Tomb" },
        { item_num: 93, item: "Totem" },
        { item_num: 94, item: "Tower" },
        { item_num: 95, item: "Trash heap" },
        { item_num: 96, item: "Tree" },
        { item_num: 97, item: "Wall" },
        { item_num: 98, item: "Waymarker" },
        { item_num: 99, item: "Well" },
        { item_num: 100, item: "Windmill" },
      ],
    },
  ],
  order: 3,
};
